In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load CSV Dataset 
df = pd.read_csv('iris.csv')

# Encode Target Y (Species)
le = LabelEncoder()
df['species'] = le.fit_transform(df['species']) 

# Fitur (x) dan target (y)
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df['species']

# Data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# K-Nearest Neighbors (KNN)
k = 5 
model = KNeighborsClassifier(n_neighbors=k)
model.fit(X_train_scaled, y_train)

# Prediksi
y_pred = model.predict(X_test_scaled)

# Evaluasi model
accuracy = accuracy_score(y_test, y_pred)
print(f"Akurasi: {accuracy * 100:.2f}%")
print("\nLaporan Klasifikasi:")
print(classification_report(y_test, y_pred))
print("\nMatriks Konfusi:")
print(confusion_matrix(y_test, y_pred))

#input data dari User
print("\n" + "="*40)
print("SISTEM IDENTIFIKASI BOTANI: SPESIES BUNGA IRIS")
print("="*40)
print("Silakan masukkan hasil pengukuran spesimen Anda:")

try:
    sepal_l = float(input("Masukkan Sepal Length (cm): "))
    sepal_w = float(input("Masukkan Sepal Width (cm) : "))
    petal_l = float(input("Masukkan Petal Length (cm): "))
    petal_w = float(input("Masukkan Petal Width (cm) : "))

    data_spesimen = pd.DataFrame([[sepal_l, sepal_w, petal_l, petal_w]], 
                                 columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
    spesimen_scaled = scaler.transform(data_spesimen)
    prediksi_nomor = model.predict(spesimen_scaled)
    spesies_terdeteksi = le.inverse_transform(prediksi_nomor)

    print("\n" + "-"*40)
    print(f"HASIL ANALISIS SPESIMEN:")
    print(f"Model memprediksi spesies ini adalah: IRIS {spesies_terdeteksi[0].upper()}")
    print("-"*40)

except ValueError:
    print("\nError: Mohon masukkan angka yang valid untuk pengukuran.")

Akurasi: 100.00%

Laporan Klasifikasi:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Matriks Konfusi:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

SISTEM IDENTIFIKASI BOTANI: SPESIES BUNGA IRIS
Silakan masukkan hasil pengukuran spesimen Anda:


Masukkan Sepal Length (cm):  6.1
Masukkan Sepal Width (cm) :  5.1
Masukkan Petal Length (cm):  3.2
Masukkan Petal Width (cm) :  4



----------------------------------------
HASIL ANALISIS SPESIMEN:
Model memprediksi spesies ini adalah: IRIS VIRGINICA
----------------------------------------
